generalInformation:
  serviceAdminEmail: jarro06@gmail.com
  gheUsername: jarro06
  billingAccount: ""
  billingTeamName: ""
  gheToken: ""
  adpAccessToken: ""
jira:
  adminToken: ""
  projectKey: ""
  projectName: ""
  leadUsername: jarro06
  documentationUrl: ""
projectInformation:
  projectName: MÃ³j super nowy projekt
  projectShortName: nowy_projekt1410
  buildType: maven
  testInstance: true
  preprodInstance: true
  uatInstance: true
cloudService:
  awsOrAzure: aks
  deploymentLocation: ""
  acpOrCRP: ""
  displayName: ""
  version: ""
  productionCluster: false
  subscriptionId: ""
  enableStorageProvisioning: true
  ingressSubnetName: ""
  clusterSubnetName: ""
  adAdminGroupName: ""
  adViewerGroupName: ""
  adEditorGroupName: ""
  privateDnsZone: ""
  awsAccountId: ""
  instanceType: ""
  r53HostedZoneDomainName: ""
  sshWorkerKey: ""
  availabilityZones: ""
  az1HarmonizedSubnetId: ""
  az1WorkerSubnetId: ""
  az1PodSubnetId: ""
  az2HarmonizedSubnetId: ""
  az2WorkerSubnetId: ""
  az2PodSubnetId: ""
  az3HarmonizedSubnetId: ""
  az3WorkerSubnetId: ""
  az3PodSubnetId: ""
  workerSecurityGroupIds: ""
  ingressSecurityGroupIds: ""
  customDefinedAutomationAdminRole: ""
automationService:
  jenkinsOrGithubActions: jenkins
  jenkinsWebhook: mywebhook.pl
gheOrganisation:
  organisationName: jarro06
  isNew: false
testingTools:
  sonarQube: true
